name: Test
on:
  push:
    branches:
      - main

jobs:
  autodiff:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        package:
          - ForwardDiff
          - ReverseDiff
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - name: "Run tests"
        run: |
            julia --color=yes --project=test/${{ matrix.package }} -e 'using Pkg; Pkg.instantiate()'
            julia --color=yes --project=test/${{ matrix.package }} --threads=auto --check-bounds=yes test/${{ matrix.package }}/runtests.jl
        shell: bash